export const USER_FIREBASE_TOKEN_MAX_LENGTH = 162;

export const USER_NICKNAME_MAX_LENGTH = 13;
export const USER_NICKNAME_MIN_LENGTH = 3;

export const USER_EMAIL_MAX_LENGTH = 320;
export const USER_EMAIL_MIN_LENGTH = 3;

export const USER_ENCRYPTED_PASSWORD_MAX_LENGTH = 200;

export const USER_PLAIN_PASSWORD_MAX_LENGTH = 24;
export const USER_PLAIN_PASSWORD_MIN_LENGTH = 6;

export const COMMENT_CONTENTS_MAX_LENGTH = 150;
export const COMMENT_CONTENTS_MIN_LENGTH = 1;

export const QUESTION_CONTENTS_MAX_LENGTH = 150;
export const QUESTION_CONTENTS_MIN_LENGTH = 1;
